version: "3.1"
services:
  springboot-app:
    container_name: jpaworkout
    image: springboot-app1
    restart: always
    build: .
    ports:
      - "8012:8080"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: gopi123
      MYSQL_PORT: 3306
      MYSQL_DATABASE: root
  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: gopi123
      MYSQL_DATABASE: root
    volumes:
       - C:\Users\Admin\Desktop\db:/var/lib/mysql
    ports:
      - "3307:3306"

      
 
#
#networks:
#  spring-microservices-network:
#    driver: bridge
